### PR TITLE
Drop kernel header dependency and add ci

### PR DESCRIPTION
**Pull request by awelzel**
Based on findings and discussion in zeek/zeek#2401, remove the dependency on kernel headers that does not exist today and likely never really has.

Also adds an ad-hoc github action and Dockerfile to build on lts, feature and nightly. That's on Debian only, but hey.

### CODE REVIEW

**Comment by awelzel** [comment]
@J-Gras - think this is ready to look at. I'll use that branch in zeek/zeek#2401 which will test a bunch more distros.

**Comment by J-Gras** [comment]
I would prefer to keep the `--with-kernel` option so that it is still possible to point to a specific version. For now it might also make sense to keep the `--with-latest-kernel` so that we don't break established build pipelines and drop it with a new major release. What do you think?

Regarding CI, I was aiming at integrating the scripts from the official [template](https://github.com/zeek/package-template).

**Comment by awelzel** [comment]
> I would prefer to keep the `--with-kernel` option so that it is still possible to point to a specific version. For now it might also make sense to keep the `--with-latest-kernel` so that we don't break established build pipelines and drop it with a new major release. What do you think?

Keeping the options for backwards compat is a good point, though I'm also happy to break setups so people can clean up there CI pipelines ;-)

As of actually having those flags do something, I wouldn't worry. It's also almost 10 years that PACKET_FANOUT exists if I googled correctly, so every distro should have up-to-date headers coming in through libc. It also seems setting the right include flags has never worked, anyway, so that would actually need to be implemented and tested. Again, IMO for very little value.

https://github.com/J-Gras/zeek-af_packet-plugin/blob/master/CMakeLists.txt#L10-L11

Let me address the first point.

> Regarding CI, I was aiming at integrating the scripts from the official [template](https://github.com/zeek/package-template).

Oh, pardon my zkg package template ignorance/uninformedness :-) I'll see how this can be added. The "nice" part about an ad-hoc Dockerfile compared to github actions is that one can run those without extra infrastructure locally. Not sure the zkg github actions allows for easy testing.

Let me see if I can copy-paste-integrate those templates. If there's more to that, I'll punt it ;-)

**Comment by awelzel** [comment]
> Let me see if I can copy-paste-integrate those templates. If there's more to that, I'll punt it ;-)

Seems that's not-quite-functional (https://github.com/zeek/action-zkg-install/issues/5)

I'm reverting to the initial version.

**Comment by awelzel** [comment]
> Seems that's not-quite-functional (https://github.com/zeek/action-zkg-install/issues/5)
> I'm reverting to the initial version.

I've added it back after understanding the issue. The current state is that it's using the zkg template github actions and separately `zeekurity/zeek` image ones.

@J-Gras - should now be okay for another look and see if you'd be okay with it as is.

**Pull request merged**
